# Generated by Django 3.0.2 on 2020-01-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
