# Generated by Django 3.0.2 on 2020-01-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_messages_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=20)),
                ('username', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=30)),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
